version: "3.9"

services:
  mage:
    build: .
    container_name: mage_citibike
    ports:
      - "6789:6789"
    volumes:
      - ./:/app/citibike_project
      - ./data:/app/data
      - ./database.db:/app/database.db
    environment:
      - PYTHONPATH=/app/citibike_project
      - DATA_DIR=/app/data
      - DB_PATH=/app/database.db
      - SLACK_WEBHOOK_URL=https://hooks.slack.com/services/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
    restart: unless-stopped
